### ISSUE TITLE
Random segfault after some time

### ISSUE THREAD

**Issue by nico-izo** [euroelessar/qutim#393]
Not easily reproducible, usually occurs after 8-20 hours.

It seems that some object get deleted while having some pending events

```
Thread 1 "qutim" received signal SIGSEGV, Segmentation fault.
0x00007ffff698c32d in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) where
#0  0x00007ffff698c32d in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff69e13ae in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff69e18d1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff47bd7d7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff47bda40 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff47bdaec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff69e248f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff698a0fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff699290c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00005555555807e6 in main (argc=1, argv=0x7fffffffdd38) at /build/qutim-UA9c1_/qutim-0.4.0+201611042301/src/bin/main.cpp:56
```

and

```
#0  QScopedLoopLevelCounter::QScopedLoopLevelCounter (threadData=0x0, this=<synthetic pointer>) at ../../include/QtCore/5.5.1/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:289
#1  QCoreApplication::notifyInternal (this=0x7fff170f4800, receiver=0x16077d0, event=event@entry=0x7fff170f4550) at kernel/qcoreapplication.cpp:964
#2  0x00007f703079d5ed in QCoreApplication::sendEvent (event=0x7fff170f4550, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
#3  QTimerInfoList::activateTimers (this=0xa40d30) at kernel/qtimerinfo_unix.cpp:637
#4  0x00007f703079daf1 in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:177
#5  0x00007f702e56b1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f702e56b400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f702e56b4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f703079e7eb in QEventDispatcherGlib::processEvents (this=0xa877e0, flags=...) at kernel/qeventdispatcher_glib.cpp:420
#9  0x00007f7030745b4a in QEventLoop::exec (this=this@entry=0x7fff170f4790, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#10 0x00007f703074dbec in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
#11 0x000000000042c30e in main (argc=3, argv=0x7fff170f5cc8) at /build/qutim-HL59at/qutim-0.4.0+201611101314/src/bin/main.cpp:56
```

**Comment by nico-izo** [comment]
Valgrind output:
http://paste.ubuntu.com/23484431/

(still no crash after two days under valgrind)

**Comment by nico-izo** [comment]
Nope, it's **attempt**, not actual closing.
